apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders-container
          image: ukrainiansoldier/orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Use the pod name as a unique client ID
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: MONGO_URI
              value: "mongodb://orders-mongo-service:27017/orders"
            - name: NATS_URL
              value: "nats://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
