apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments-container
          image: ukrainiansoldier/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Use the pod name as a unique client ID
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: secret_key
            - name: STRIPE_WEB_HOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: web_hook_key
            - name: MONGO_URI
              value: "mongodb://payments-mongo-service:27017/payments"
            - name: NATS_URL
              value: "nats://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
